name: Deploy Logic App to QA

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Logic App to QA
        run: |
          az deployment group create --resource-group YourQAResourceGroup --template-file ${{ github.workspace }}/path/to/logic-app-template.json --parameters ${{ github.workspace }}/path/to/logic-app-parameters.json
#${{ github.workspace }} this would represent the core repository where the logic apps ARM templates are stored.
