name: Deploy Logic App to QA

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Az PowerShell module
        run: |
          if ('${{ inputs.skipAzModuleInstallation }}' -ne 'true') {
            Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force
          }
        shell: pwsh

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Logic App to QA
        run: |
          pwsh -c "az deployment group create --resource-group TripleApocQA --template-file ${{ github.workspace }}/src/LogicappsARM/template.json --parameters ${{ github.workspace }}/src/LogicappsARM/parameters.json"
         # ${{ github.workspace }} represents the core repository where the logic apps ARM templates are stored.
