on: 
  push:
    branches:
      - 'main'

name: Web App Creation
jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:

        # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: ././LogicappARMTemplates/template.json
          parameters: ././LogicappARMTemplates/parameters.json 

        # output containerName variable from template
      - run: echo ${{ steps.deploy.outputs.containerName }}
