name: Deploy ARM template

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install azure-actions-arm-deploy
        run: npm install -g azure-actions-arm-deploy
      - name: Deploy ARM template
        run: azure/arm-deploy@v1
