



        - name: Import Logic App Workflow
           run: |
    az logic workflow import --resource-group <TargetResourceGroup> --name <LogicAppName> --workflow-name <WorkflowName> --workflow-definition @"workflow.json"
         env:
    AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}


