name: Create a Logic App



on:
  workflow_dispatch:
    inputs:
      subscriptionId:
        description: '9eb9892d-4d82-4c17-a21c-f37555c98487'
        required: true
      resourceGroupName:
        description: 'Tripleapoc_QA'
        required: true

 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on:  ubuntu-latest

 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{github.event.inputs.subscriptionId}}
          resourceGroupName: ${{github.event.inputs.resourceGroupName}}
          template: ./LogicappARMTemplates/template.json
          parameters: ./LogicappARMTemplates/parameters.json
