name: Deploy Logic App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enable GitHub Actions Debug Mode
        run: |
          echo "##[debug] GitHub Actions Debug Mode Enabled"
        shell: bash

      - name: Install Az PowerShell module
        run: |
          if ('${{ inputs.skipAzModuleInstallation }}' -ne 'true') {
            Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force
          }
        shell: pwsh

      - name: Clear GitHub Actions workspace
        run: rm -rf ${{ github.workspace }}/*

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}} # Use the appropriate secret based on the environment

      - name: Print Directory Contents
        run: |
          ls -R ${{ github.workspace }}


      - uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{github.event.inputs.subscriptionId}}
          resourceGroupName: ${{github.event.inputs.resourceGroupName}}
          template: ./LogicappsARMTemplates/parameters.json
          parameters: ./LogicappsARMTemplates/template.json

      #- name: Deploy Logic App
      #  run: |
      #   pwsh -c "az deployment group create --resource-group Tripleapoc_QA --template-file templatetest.json --parameters parameters.json"

          
