name: Migrate Logic Apps test

pool:
  name: Azure Pipelines
  demands:
  - msbuild
  - visualstudio

steps:
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1

- task: NuGetCommand@2
  displayName: 'NuGet restore'

- task: VSBuild@1
  displayName: 'Build solution **\*.sln'


- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: BundleLogicApp
    archiveFile: BundleLogicApp.zip

- task: AzureFunctionApp@1
  displayName: 'Azure Function App Deploy: FunctionDeployedByDevOps'
  inputs:
    azureSubscription: '581c5e0c-b29b-4026-aa7f-019b1a1f69c4'
    appType: functionApp
    appName: a4llogicappqa
    package: BundleLogicApp.zip

