name: Migrate Logic Apps

on:
  workflow_dispatch:
    inputs:
      subscriptionId:
        description: '9eb9892d-4d82-4c17-a21c-f37555c98487'
        required: true
      resourceGroupName:
        description: 'Tripleapoc_QA'
        required: true

jobs:
  migrate:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Azure Login
        uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

 
      - name: Get ARM templates
        run: |
          echo "Getting ARM templates..."
          ls ./LogicappARMTemplates
      - name: Migrate ARM templates
        uses: azure/arm-deploy@v4
        with:
              subscriptionId: ${{github.event.inputs.subscriptionId}}
              resourceGroupName: ${{github.event.inputs.resourceGroupName}}
              template: ./LogicappARMTemplates/template.json
              parameters: ./LogicappARMTemplates/parameters.json
      - name: Deploy ARM Template
      # define required arguments for AZ CLI command 
        env:
          RESOURCE_GROUP: Tripleapoc_QA
          TEMPLATEFILE: ./LogicappARMTemplates/template.json
          PARAMETERSFILE: ./LogicappARMTemplates/parameters.json      
        uses: azure/CLI@v1
        with:
      # Execute AZ CLI command
          inlineScript: |
            az deployment group create --resource-group $RESOURCE_GROUP --template-file $TEMPLATEFILE --parameters $PARAMETERSFILE

          
