name: Migrate Logic Apps

on:
  workflow_dispatch:
    inputs:
      subscriptionId:
        description: '9eb9892d-4d82-4c17-a21c-f37555c98487'
        required: true
      resourceGroupName:
        description: 'Tripleapoc_QA'
        required: true

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Azure Login
        uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

 
      - name: Get ARM templates
        run: |
          echo "Getting ARM templates..."
          ls ./LogicappARMTemplates
      - name: Migrate ARM templates
        run: |
            azure/arm-deploy@v1
            with:
              subscriptionId: ${{github.event.inputs.subscriptionId}}
              resourceGroupName: ${{github.event.inputs.resourceGroupName}}
              template: ./LogicappARMTemplates/template.json
              parameters: ./LogicappARMTemplates/parameters.json
