name: Migrate Logic Apps

on:
  workflow_dispatch:
    inputs:
      subscriptionId:
        description: 'd6376798-ade5-4b19-b744-02fe1939dd9e'
        required: true
      resourceGroupName:
        description: 'Tripleapoc_QA'
        required: true
      LogicAppName:
        description: 'a4llogicappqa'
        required: true

jobs:
  migrate:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Azure Login
        uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Create project folder
        run: |
         mkdir output
         cp 'workflow.json' 'output/'
         #cp 'parameters.json' 'output/'
         #cp 'connections.json' 'output/'
         cp -r 'Stateful' 'output/'
         
      - name: Easy Zip Files
        uses: vimtor/action-zip@v1
        with:
         dest: '${{ github.run_id }}.zip'
         files: output/


      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
         app-name: ${{github.event.inputs.LogicAppName}}
         package: '${{ github.run_id }}.zip'
         publish-profile: ${{ secrets.PUBLISH_PROFILE }} 